# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NTI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NTI
  pod 'RxCocoa'
  pod 'RxSwift'
  pod 'RxDataSources'
  pod 'RxSwiftExt'
  pod 'MBProgressHUD'
  pod 'SwiftLint', '~> 0.27'
  pod 'Swinject'
  pod 'Sourcery'
  pod 'SwiftyMocky'
  pod 'ReachabilitySwift'
  target 'NTITests' do
    inherit! :search_paths
    # Pods for testing
       pod 'RxBlocking'
       pod 'RxTest'
       pod 'Swinject'
  end

  target 'NTIUITests' do
    # Pods for testing
  end

end
